// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types
/* eslint-disable @typescript-eslint/no-unused-vars */

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport, Metadata, Viewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]>; searchParams: Promise<Record<string, string | string[] | undefined>> }> | ((props: { params: Promise<ParamMap[Route]>; searchParams: Promise<Record<string, string | string[] | undefined>> }) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<Record<string, unknown>[]> | Record<string, unknown>[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]>; searchParams: Promise<Record<string, string | string[] | undefined>> },
    parent: ResolvingMetadata
  ) => Promise<Record<string, unknown>> | Record<string, unknown>
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]>; searchParams: Promise<Record<string, string | string[] | undefined>> },
    parent: ResolvingViewport
  ) => Promise<Record<string, unknown>> | Record<string, unknown>
  metadata?: Record<string, unknown>
  viewport?: Record<string, unknown>
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]>; children: React.ReactNode }> | ((props: { params: Promise<ParamMap[Route]>; children: React.ReactNode }) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<Record<string, unknown>[]> | Record<string, unknown>[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> },
    parent: ResolvingMetadata
  ) => Promise<Record<string, unknown>> | Record<string, unknown>
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> },
    parent: ResolvingViewport
  ) => Promise<Record<string, unknown>> | Record<string, unknown>
  metadata?: Metadata
  viewport?: Viewport
}


// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../app/(public)/page")
  type __Check = __IsExpected<typeof handler>
}


// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../app/layout")
  type __Check = __IsExpected<typeof handler>
}
